// <auto-generated />
namespace TicketsDemo.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddBookingAgencies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBookingAgencies));
        
        string IMigrationMetadata.Id
        {
            get { return "202010181432334_AddBookingAgencies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
